### ISSUE TITLE
特定ユーザーでログインするとアプリが閉じてしまう

### ISSUE THREAD

**Issue by matsujirushi** [SeeedJP/Wio_Link_Android_App#13]
特定ユーザーでログインすると、一瞬、ノードの一覧が表示された後、アプリが閉じてしまう。

**Comment by matsujirushi** [comment]
`Collections.sort()`内部で`java.lang.IllegalArgumentException: Comparison method violates its general contract!`が発生している。

**エラーメッセージ:**
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cc.seeed.iot.ap, PID: 15751
    java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeCollapse(TimSort.java:441)
        at java.util.TimSort.sort(TimSort.java:245)
        at java.util.Arrays.sort(Arrays.java:1492)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:206)
        at cc.seeed.iot.ui_main.MainScreenActivity$2.handleMessage(MainScreenActivity.java:319)
```

**コード:**
```
Collections.sort(nodes, new ComparatorUtils.ComparatorNode());
```

**nodes:**
![image](https://user-images.githubusercontent.com/8079404/224872255-e1896744-4abf-40b8-b774-df6ed580c1c7.png)

**Comment by matsujirushi** [comment]
ノードが32以上のユーザーでエラーが発生すると思われる。

> [Comparison method violates its general contract! が発生](https://pgse.seesaa.net/article/400441842.html)
> 
> 要素数が32未満のときは処理のフローが異なっていました。

**Comment by matsujirushi** [comment]
同一が実装されていない。

```
    public static class ComparatorNode implements Comparator {
        public int compare(Object arg0, Object arg1) {
            Node node1 = (Node) arg0;
            Node node2 = (Node) arg1;

            if (node1.online && !node2.online) {
                return -1;
            } else {
                return 1;
            }
        }
    }
```
